from django.contrib import admin
from .models import User
admin.site.register(User)



'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxMjM0MjkwLCJqdGkiOiI5ODMwNWJiMDEwM2U0ZmEyYmNkNWZkYWQzZjQyYTgwMSIsInVzZXJfaWQiOjF9.BHuEShTpuzfYYKWMBuotCx3Sc7PKIy90mqMqJyZF7bo'