# Generated by Django 3.2 on 2022-12-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='6YKsRFwHv5fokmbcJ9LQ', max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
