# Generated by Django 3.2 on 2022-12-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='uaJAYnFkyhU6vWqbScBl', max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
