# Generated by Django 3.2 on 2022-12-16 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genrestitle',
            old_name='title',
            new_name='title_id',
        ),
        migrations.RemoveField(
            model_name='genrestitle',
            name='genre',
        ),
        migrations.AddField(
            model_name='genrestitle',
            name='genre_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reviews.genre'),
            preserve_default=False,
        ),
    ]
